name: GTY

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'

    # install dart flog global
    - name: Install dart flog
      run: dart pub global activate dart_frog_cli

    # install dependencies in server folder
    - name: Install dependencies in server
      run: cd server && dart pub get

    - run: flutter pub get
    - run: flutter test
    - run: flutter analyze
